import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ms' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  ms: {
    'nav.more': 'Lagi',
    'nav.learn': 'Ilmu',
    'nav.pray': 'Ibadah',
    'nav.ummah': 'Ummah',
    'nav.search': 'Cari...',
    'nav.home': 'Dashboard',
    'nav.mualaf': 'Mualaf Hub',
    'nav.quran': 'Al-Quran',
    'nav.iqra': 'Iqra\'',
    'nav.muqaddam': 'Muqaddam',
    'nav.hadis': 'Hadis',
    'nav.jadual': 'Jadual Solat',
    'nav.tracker': 'Tracker',
    'nav.ramadan': 'Ramadan',
    'nav.zikir': 'Zikir',
    'nav.99names': '99 Nama',
    'nav.zakat': 'Zakat',
    'nav.kiblat': 'Kiblat',
    'nav.doa': 'Doa',
    'nav.sirah': 'Sirah',
    'nav.kelas': 'Kelas Online',
    'nav.komuniti': 'Komuniti',
    'nav.derma': 'Derma',
    'nav.tetapan': 'Tetapan',
    'nav.about': 'Mengenai Developer',
    'nav.login': 'Log Masuk',
    'nav.logout': 'Log Keluar',
    'nav.saham': 'Saham',
    'nav.menu': 'Menu Utama',
    'nav.dana': 'Dana Operasi',
    'nav.infark': 'INFARK SEKARANG',
    'nav.dana_desc': 'Niyyah kekal tanpa iklan sumbangan anda',
    'nav.tagline': 'Celik Ummah',

    'mualaf.title': 'Mualaf Hub',
    'mualaf.subtitle': 'Pusat Bimbingan Mualaf',
    'mualaf.desc': 'Bimbingan ringkas, langkah demi langkah untuk perjalanan iman anda.',
    'mualaf.tab.basics': 'Asas Ibadah',
    'mualaf.tab.doa': 'Doa Harian',
    'mualaf.tab.solat': 'Panduan Solat',
    'mualaf.tab.quran': 'Quran Rumi',
    'mualaf.tab.support': 'Sokongan Emosi',
    'mualaf.tab.community': 'Mentor',
    'mualaf.module.type': 'Modul Pembelajaran',
    'mualaf.rumi.notice': 'Bahagian ini khas untuk mereka yang belum mahir membaca teks Arab. Gunakan teks Rumi sebagai bimbingan sementara.',
    'mualaf.rumi.label': 'Teks Rumi',
    'mualaf.maksud.label': 'Maksud',
    'mualaf.motivation.title': 'Motivasi Harian',
    'mualaf.qa.title': 'Ruang Soal Jawab (Anonim)',
    'mualaf.qa.desc': 'Tanya soalan anda secara peribadi tanpa nama. Mentor kami akan menjawab secara tertutup.',
    'mualaf.qa.placeholder': 'Contoh: Bagaimana hadapi keluarga yang belum tahu saya masuk Islam?',
    'mualaf.qa.submit': 'Hantar Soalan',
    'mualaf.qa.login_required': 'Sila log masuk untuk bertanya.',
    'mualaf.qa.history': 'Pertanyaan Anda',
    'mualaf.qa.waiting': 'Menunggu Jawapan...',
    'mualaf.qa.mentor_reply': 'Jawapan Mentor',
    'mualaf.community.chat': 'Bilik Sembang Mualaf',
    'mualaf.community.chat_desc': 'Komuniti tertutup untuk berbincang dengan rakan seperjuangan.',
    'mualaf.community.mentors': 'Mentor Berdaftar',
    'mualaf.community.online': 'Online Sekarang',
    'mualaf.community.verified': 'Disahkan Admin',
    'mualaf.community.chat_btn': 'Chat',
    'mualaf.community.no_mentors': 'Pendaftaran Mentor Sedang Diproses',
    'mualaf.emotion_tip': 'Petua Emosi',
    'mualaf.emotion_text': 'Amalkan zikir "La ilaha illa Allah" (Tiada Tuhan melainkan Allah) apabila merasa gelisah. Ia memberikan ketenangan yang luarbiasa kepada hati.',
    'mualaf.community.tg': 'Grup Telegram',
    'mualaf.community.tg_note': 'Pengesahan Admin Diperlukan',
    'mualaf.community.wa': 'Sokongan WhatsApp',
    'mualaf.community.wa_note': 'Respon Pantas (24/7)',
    'mualaf.community.lecturer': 'Pensyarah Agama',
    'mualaf.community.book_btn': 'Tempah Sesi',
    'mualaf.solat.title': 'Panduan Solat Langkah Demi Langkah',
    'mualaf.solat.subtitle': 'Bimbingan Lengkap dari Niat hingga Salam',
    'mualaf.solat.important': 'Nota Penting',
    'mualaf.solat.step1.title': 'Niat Solat',
    'mualaf.solat.step1.desc': 'Niat di dalam hati mengikut waktu solat yang dikerjakan.',
    'mualaf.solat.step2.title': 'Takbiratul Ihram',
    'mualaf.solat.step2.desc': 'Mengangkat tangan dan mengucap "Allahu Akbar".',
    'mualaf.solat.step3.title': 'Bacaan Al-Fatihah',
    'mualaf.solat.step3.desc': 'Rukun wajib yang perlu dibaca dengan tenang.',
    'mualaf.solat.step4.title': 'Rukuk',
    'mualaf.solat.step4.desc': 'Membongkokkan badan dengan tangan di lutut.',
    'mualaf.solat.step5.title': 'I\'tidal',
    'mualaf.solat.step5.desc': 'Berdiri tegak semula selepas rukuk.',
    'mualaf.solat.step6.title': 'Sujud',
    'mualaf.solat.step6.desc': 'Meletakkan dahi, hidung, tapak tangan, lutut dan jari kaki di lantai.',
    'mualaf.solat.note1': 'Pastikan badan, pakaian dan tempat bersih dari najis.',
    'mualaf.solat.note2': 'Mengadap ke arah Kiblat (Guna fungsi Kiblat dalam app).',
    'mualaf.solat.note3': 'Menutup aurat dengan sempurna.',
    'mualaf.solat.note4': 'Masuk waktu solat yang betul.',
    
    // Dashboard
    'dash.title': 'Utama',
    'dash.greeting': 'Assalamualaikum, {name}',
    'dash.greeting_default': 'Assalamualaikum, Ya Akhi/Ukhti',
    'dash.prayer_current': 'Waktu Solat Terkini',
    'dash.prayer_next': 'Solat Seterusnya',
    'dash.prayer_waiting': 'Mengira waktu...',
    'dash.prayer_running': 'Sedang Berjalan ({time}m)',
    'dash.prayer_remaining': '{time} lagi',
    'dash.widget_btn': 'AKTIFKAN WIDGET',
    'dash.jadual_today': 'Jadual Hari Ini',
    'dash.jadual_full': 'Lihat Jadual Penuh',
    'dash.ayat_title': 'Ayat Pilihan Hari Ini',
    'dash.ayat_verse': 'Wahai orang-orang yang beriman! Mintalah pertolongan (kepada Allah) dengan sabar dan solat; sesungguhnya Allah menyertai (menolong) orang-orang yang sabar.',
    'dash.tafsir_btn': 'LIHAT TAFSIR',
    'dash.audio_btn': 'IKUTI AUDIO',
    'dash.hadis_title': 'Pustaka Hadis',
    'dash.hadis_loading': 'Memuatkan pesan Rasulullah...',
    'dash.story_title': 'Inspirasi Ummah',
    'dash.story_author': 'Oleh: {name}',
    'dash.story_sample': '"Kisah bagaiman kejujuran membawa saya kepada rezeki yang tidak disangka-sangka..."',
    'dash.status_active': 'Status: Ahli Aktif',

    // Ramadan
    'ramadan.title': 'Dashboard Ramadan',
    'ramadan.subtitle': 'Ramadan Al-Mubarak 1447H',
    'ramadan.desc': 'Satu bulan penuh rahmat, keampunan, dan pelepasan dari api neraka. Jejaki amalan anda setiap hari.',
    'ramadan.select_day': 'Pilih Hari',
    'ramadan.day_count': 'Hari Ke-{num}',
    'ramadan.checklist': 'Checklist Amalan',
    'ramadan.progress': 'Kemajuan',
    'ramadan.deed.fasting': 'Berpuasa',
    'ramadan.deed.tarawih': 'Solat Tarawih',
    'ramadan.deed.tadarus': 'Tadarus Al-Quran',
    'ramadan.deed.sedekah': 'Sedekah',
    'ramadan.deed.witir': 'Solat Witir',
    'ramadan.deed.iktikaf': 'Iktikaf',
    'ramadan.niat.title': 'Niat Puasa Ramadan',
    'ramadan.niat.arabic': 'نَوَيْتُ صَوْمَ غَدٍ عَنْ أَدَاءِ فَرْضِ شَهْرِ رَمَضَانَ هَذِهِ السَّنَةِ لِلَّهِ تَعَالَى',
    'ramadan.niat.transliteration': 'Nawaitu sawma ghadin \'an ada\'i fardhi shahri Ramadhana hadhihis-sanati lillahi ta\'ala.',
    'ramadan.niat.meaning': 'Sahaja aku berpuasa esok hari bagi menunaikan fardu bulan Ramadhan tahun ini kerana Allah Ta\'ala.',
    'ramadan.break.title': 'Doa Berbuka Puasa',
    'ramadan.break.arabic': 'اللَّهُمَّ لَكَ صُمْتُ وَبِكَ آمَنْتُ وَعَلَى رِزْقِكَ أَفْطَرْتُ',
    'ramadan.break.transliteration': 'Allahumma laka sumtu wa bika amantu wa \'ala rizqika aftartu.',
    'ramadan.break.meaning': 'Ya Allah, untuk-Mu aku berpuasa, kepada-Mu aku beriman, dan dengan rezeki-Mu aku berbuka.',
    'ramadan.quote.title': 'Mutiara Kata',
    'ramadan.quote.text': '"Barangsiapa yang berpuasa Ramadan dengan penuh keimanan dan mengharap pahala (dari Allah), maka akan diampuni dosa-dosanya yang telah lalu."',
    'ramadan.quote.author': 'Hadis Riwayat Bukhari & Muslim',

    // Zakat
    'zakat.title': 'Kalkulator Zakat',
    'zakat.subtitle': 'Pengurusan Harta & Keberkatan',
    'zakat.desc': 'Sucikan harta anda dengan Zakat. Salah satu Rukun Islam yang menjamin keseimbangan ekonomi Ummah.',
    'zakat.wealth_label': 'Jumlah Harta Terkumpul (Simpanan/Pelaburan)',
    'zakat.status_title': 'Status Zakat',
    'zakat.qualify_true': 'Harta anda layak dikenakan Zakat pada kadar 2.5%.',
    'zakat.qualify_false': 'Harta anda belum cukup nisab (RM {nisab}) buat masa ini.',
    'zakat.type_label': 'Pilih Jenis Zakat',
    'zakat.type.saving': 'Simpanan',
    'zakat.type.income': 'Pendapatan',
    'zakat.type.gold': 'Emas',
    'zakat.type.business': 'Perniagaan',
    'zakat.pay_label': 'Jumlah Perlu Dibayar',
    'zakat.info_rate': 'Kadar 2.5% digunakan untuk perkiraan zakat harta umum.',
    'zakat.pay_btn': 'Bayar Sekarang',
    'zakat.footer': 'Kalkulator ini menyediakan pengiraan ANGGARAN sahaja. Sila rujuk Pusat Zakat Negeri masing-masing untuk pengiraan lebih tepat.',

    'prayer.fajr': 'Subuh',
    'prayer.syuruk': 'Syuruk',
    'prayer.dhuhr': 'Zohor',
    'prayer.asr': 'Asar',
    'prayer.maghrib': 'Maghrib',
    'prayer.isha': 'Isyak',
    
    // Basics Modules
    'mualaf.syahadah.title': 'Cara Mengucap Syahadah',
    'mualaf.syahadah.desc': 'Ikrar penyaksian masuk Islam.',
    'mualaf.mandi.title': 'Cara Mandi Wajib (Junub)',
    'mualaf.mandi.desc': 'Penyucian diri secara spiritual selepas hadas besar.',
    'mualaf.wuduk.title': 'Cara Wuduk (Ambil Air Sembahyang)',
    'mualaf.wuduk.desc': 'Bersuci sebelum menunaikan solat.',
    'mualaf.tayammum.title': 'Cara Tayammum (Guna Tanah)',
    'mualaf.tayammum.desc': 'Bersuci tanpa air dalam keadaan darurat.',
    'mualaf.solat_module.title': 'Cara Solat (Lengkap)',
    'mualaf.solat_module.desc': 'Panduan asas pergerakan solat fardu.',
    'mualaf.puasa.title': 'Cara Puasa Ramadhan',
    'mualaf.puasa.desc': 'Ibadah menahan diri di bulan mulia.',
    'mualaf.zakat.title': 'Cara Zakat Fitrah',
    'mualaf.zakat.desc': 'Penyucian harta dan bantuan kpd yang memerlukan.',
    'mualaf.korban.title': 'Cara Korban & Aqiqah',
    'mualaf.korban.desc': 'Ibadah sembelihan tanda syukur.',

    // Doa
    'doa.wakeup.title': 'Doa Bangun Tidur',
    'doa.wakeup.maksud': 'Segala puji bagi Allah yang menghidupkan kami selepas mematikan kami dan kepada-Nya kami kembali.',
    'doa.toilet_in.title': 'Doa Masuk Tandas',
    'doa.toilet_in.maksud': 'Ya Allah, sesungguhnya aku berlindung kepada-Mu dari gangguan syaitan jantan dan syaitan betina.',
    'doa.toilet_out.title': 'Doa Keluar Tandas',
    'doa.toilet_out.maksud': 'Aku memohon keampunan-Mu. Segala puji bagi Allah yang telah menghilangkan kesakitan dariku dan menyembuhkanku.',
    'doa.eat_before.title': 'Doa Sebelum Makan',
    'doa.eat_before.maksud': 'Ya Allah, berkatilah rezeki yang Engkau berikan dan peliharalah kami dari azab api neraka.',
    'doa.eat_after.title': 'Doa Lepas Makan',
    'doa.eat_after.maksud': 'Segala puji bagi Allah yang telah memberi kami makan dan minum, serta menjadikan kami orang-orang Muslim.',
    'doa.house_out.title': 'Doa Keluar Rumah',
    'doa.house_out.maksud': 'Dengan nama Allah, aku bertawakal, tiada daya melainkan dengan pertolongan Allah.',
    'doa.house_in.title': 'Doa Masuk Rumah',
    'doa.house_in.maksud': 'Ya Allah, aku memohon kepada-Mu sebaik-baik tempat masuk dan sebaik-baik tempat keluar. Dengan nama Allah kami masuk dan dengan nama Allah kami keluar dan kepada Allah Tuhan kami, kami berserah diri.',
    'doa.travel.title': 'Doa Naik Kenderaan',
    'doa.travel.maksud': 'Maha Suci Allah yang telah memudahkan kenderaan ini untuk kami, sedang kami sendiri tidak terdaya menguasainya.',
    'doa.sleep.title': 'Doa Sebelum Tidur',
    'doa.sleep.maksud': 'Dengan nama-Mu ya Allah, aku mati dan aku hidup.',
    'doa.protection.title': 'Doa Mohon Perlindungan',
    'doa.protection.maksud': 'Aku berlindung dengan kalimah Allah yang sempurna dari kejahatan sekalian makhluk-Nya.',
    'doa.travel_ride.title': 'Doa Musafir',
    'doa.travel_ride.maksud': 'Maha Suci Allah yang telah memudahkan kenderaan ini untuk kami, sedang kami sendiri tidak terdaya menguasainya. Dan sesungguhnya kepada Tuhan kamilah, kami akan kembali.',
    'doa.study.title': 'Doa Ilmu',
    'doa.study.maksud': 'Wahai Tuhanku, tambahkanlah ilmuku dan luaskanlah kefahamanku.',
    'doa.rabbana.title': 'Doa Rabbana',
    'doa.rabbana.maksud': 'Wahai Tuhan kami, berilah kami kebaikan di dunia dan kebaikan di akhirat, dan peliharalah kami dari azab api neraka.',

    // Quran
    'quran.fatihah.maksud': 'Dengan nama Allah Yang Maha Pemurah lagi Maha Penyayang. Segala puji bagi Allah, Tuhan sekalian alam...',
    'quran.ikhlas.maksud': 'Katakanlah: Dia lah Allah Yang Maha Esa. Allah yang menjadi tumpuan sekalian makhluk...',
    'quran.falaq.maksud': 'Katakanlah: Aku berlindung kepada Tuhan yang menciptakan fajar, dari kejahatan makhluk-Nya...',
    'quran.nas.maksud': 'Katakanlah: Aku berlindung kepada Tuhan (yang memelihara) manusia. Raja manusia. Tuhan manusia...',
    'quran.kauthar.maksud': 'Sesungguhnya Kami telah memberi kepadamu nikmat yang banyak. Maka dirikanlah solat kerana Tuhanmu dan berkorbanlah...',
    'quran.nasr.maksud': 'Apabila datang pertolongan Allah dan kemenangan. Dan engkau melihat manusia masuk ke dalam agama Allah beramai-ramai...',
    'quran.kursi.maksud': 'Allah, tiada Tuhan melainkan Dia yang Hidup kekal lagi terus menerus mengurus makhluk...',

    // Quran Page
    'quran.title': 'Al-Quran',
    'quran.subtitle': 'Kitab Suci & Petunjuk Lengkap',
    'quran.search': 'Cari Surah...',
    'quran.loading': 'Memuatkan Surah...',
    'quran.juz': 'Juz {num}',
    'quran.verses': '{num} Ayat',
    'quran.revelation_meccan': 'Makkiyah',
    'quran.revelation_medinan': 'Madaniyah',
    'quran.last_read': 'Bacaan Terakhir',
    'quran.info_btn': 'Info Surah',
    'quran.digital_title': 'Digital',
    'quran.hadith_quote': '"Sebaik-baik kalian adalah orang yang belajar Al-Qur\'an dan mengajarkannya." (HR. Bukhari)',
    'quran.translation_label': 'Maksud Ayat',
    'quran.list_title': 'Indeks Surah',
    'quran.empty': 'Tiada surah atau ayat dijumpai.',

    // Hadis Page
    'hadis.title': 'Pustaka Hadis',
    'hadis.subtitle': 'Pesan Rasulullah (SAW)',
    'hadis.search': 'Cari hadis atau topik...',
    'hadis.loading': 'Memuatkan hadis...',
    'hadis.view_all': 'Lihat Semua {book}',
    'hadis.collection_badge': 'Koleksi Sahih & Pilihan',
    'hadis.explore_desc': 'Terokai kupasan mendalam mengenai {cat} berdasarkan riwayat-riwayat yang muktabar.',
    'hadis.status_sahih': 'Sahih',
    'hadis.transmission': 'Transmisi',
    'hadis.translation_label': 'Terjemahan Sahih',
    'hadis.meaning_title': 'Makna & Pengajaran',
    'hadis.explanation_title': 'Syarah Ringkas',
    'hadis.hints_title': 'Intipati Utama',

    // Doa Page
    'doa.title': 'Himpunan Doa',
    'doa.subtitle': 'Senjata Orang Mukmin',
    'doa.category.daily': 'Harian',
    'doa.category.prayer': 'Solat',
    'doa.category.prophets': 'Para Nabi',
    'doa.category.protection': 'Perlindungan',
    'doa.category.health': 'Kesihatan',
    'doa.category.knowledge': 'Ilmu & Rezeki',
    'doa.category.ramadan': 'Ramadan',
    'doa.all': 'Semua',
    'doa.my_saved': 'Simpanan Saya',
    'doa.add_btn': 'Tambah Doa',
    'doa.form_title': 'Tajuk Doa',
    'doa.form_title_placeholder': 'Contoh: Doa Dipermudah Urusan',
    'doa.form_arabic_placeholder': 'Tulis dalam Bahasa Arab...',
    'doa.form_trans_placeholder': 'Contoh: Bismika Allahumma...',
    'doa.form_meaning_placeholder': 'Terjemahan...',
    'doa.save_btn': 'Simpan',
    'doa.empty_title': 'Doa Tanpa Tajuk',

    // Settings
    'settings.title': 'Tetapan',
    'settings.profile': 'Profil Pengguna',
    'settings.language': 'Bahasa Aplikasi',
    'settings.location': 'Lokasi & Zon Solat',
    'settings.notifications': 'Notifikasi Azan',
    'settings.theme': 'Tema Visual',
    'settings.save_btn': 'Simpan Tetapan',
    'settings.subtitle': 'Urus profil dan peringatan anda',
    'settings.status_active': 'Status: Ahli Aktif',
    'settings.display_name': 'Nama Paparan',
    'settings.reminder_before': 'Peringatan Sebelum Azan',
    'settings.minutes': 'Minit',
    'settings.success': 'BERJAYA DISIMPAN!',
    'settings.saving': 'Menyimpan...',
    'settings.support_title': 'Sumbangan Infaq',
    'settings.support_desc': 'Aplikasi ini adalah inisiatif komuniti percuma. Jika anda ingin menyokong kos penyelenggaraan dan pembangunan, anda boleh menyumbang melalui pautan di bawah.',
    'settings.support_btn': 'Infaq Sekarang',

    // Tracker
    'tracker.title': 'Tracker Solat',
    'tracker.subtitle': 'Istiqamah itu Indah',
    'tracker.done': 'Selesai Dilaksanakan',
    'tracker.pending': 'Belum Ditanda',
    'tracker.target': 'Target Hari Ini',
    'tracker.quote': '"Amalan yang paling dicintai Allah ialah solat pada waktunya." (HR. Bukhari)',
    'tracker.reward_title': 'Ganjaran Hari Ini',
    'tracker.reward_desc': 'Banyakkan berselawat ke atas Nabi SAW untuk menambah barakah hari anda.',

    // Sirah
    'sirah.title': 'Sirah Nabawiyah',
    'sirah.subtitle': 'Menelusuri jejak kehidupan insan termulia, Nabi Muhammad SAW sebagai panduan hidup sepanjang zaman.',
    'sirah.timeline': 'Garis Masa Sejarah Islam',
    'sirah.epoch_1_title': 'Kelahiran & Zaman Kanak-kanak',
    'sirah.epoch_1_desc': 'Tahun Gajah, penyusuan Halimah As-Sa\'diyah, dan kewafatan Aminah binti Wahab.',
    'sirah.epoch_2_title': 'Zaman Belia & Perkahwinan',
    'sirah.epoch_2_desc': 'Kejujuran Al-Amin sebagai pedagang dan perkahwinan suci dengan Khadijah binti Khuwailid.',
    'sirah.epoch_3_title': 'Nubuwwah (Wahyu Pertama)',
    'sirah.epoch_3_desc': 'Peristiwa di Gua Hira\', kunjungan Jibril AS dan bermulanya dakwah secara rahsia.',
    'sirah.epoch_4_title': 'Dakwah Terbuka & Tentangan',
    'sirah.epoch_4_desc': 'Dakwah di Bukit Safa, tentangan Abu Lahab, dan penyiksaan golongan lemah.',
    'sirah.author': 'Dipetik oleh {name}',
    'sirah.read_more': 'Baca Lanjut',
    'sirah.footer_title': 'Perjalanan Belum Selesai',
    'sirah.footer_desc': 'Kami sedang dalam proses menambah lebih banyak kisah perjuangan Nabi SAW dan para Sahabat RA.',
    'sirah.notify_btn': 'Ingatkan Saya',

    // Zikir
    'zikir.title': 'Zikir & Tasbih',
    'zikir.subtitle': 'Menenangkan Hati Dengan Mengingati Allah',
    'zikir.tab.tasbih': 'Digital Tasbih',
    'zikir.tab.wird': 'Koleksi Wird',
    'zikir.counter.title': 'Jumlah Zikir',
    'zikir.btn.click': 'Ketik Untuk Zikir',
    'zikir.reset_confirm': 'Sahkan untuk set semula kiraan?',
    'zikir.vibration': 'Gegaran {status}',
    'zikir.pagi': 'Zikir Pagi',
    'zikir.petang': 'Zikir Petang',
    'zikir.mathurat': 'Ma\'thurat Sughra',
    'zikir.meaning.subhanallah': 'Maha Suci Allah',
    'zikir.meaning.alhamdulillah': 'Segala Puji Bagi Allah',
    'zikir.meaning.allahuakbar': 'Allah Maha Besar',
    'zikir.meaning.lailahaillallah': 'Tiada Tuhan Melainkan Allah',
    'zikir.meaning.astaghfirullah': 'Aku Memohon Keampunan Allah',

    // 99 Names
    'names.title': 'Asma\'ul Husna',
    'names.subtitle': '99 Nama-Nama Allah',
    'names.quote': '"Dan bagi Allah jualah nama-nama yang baik (dan mulia), maka berdoalah kepadaNya dengan menyebut nama-nama itu." (Surah Al-A\'raf: 180)',
    'names.search': 'Cari Nama Allah...',
    'names.detail_btn': 'Butiran',

    // Qibla
    'qibla.title': 'Kiblat',
    'qibla.subtitle': 'Hala Tuju Ibadah Dimana Sahaja',
    'qibla.direction': 'Arah Kiblat',
    'qibla.activate_btn': 'Aktifkan Sensor Kompas',
    'qibla.notice': 'Letakkan telefon di atas permukaan rata. Pastikan GPS anda aktif untuk ketepatan maksimum.',

    // Jadual Solat
    'jadual.title': 'Takwim Solat',
    'jadual.subtitle': 'Jadual Waktu Solat Rasmi JAKIM',
    'jadual.location_btn': 'Guna Lokasi Saya',
    'jadual.locating': 'Mengesan...',
    'jadual.detect_error': 'Gagal mengesan lokasi. Sila pastikan kebenaran lokasi telah diberikan.',
    'jadual.print': 'Cetak Jadual',
    'jadual.date_day': 'Tarikh & Hari',
    'jadual.imsak': 'Imsak',
    'jadual.subuh': 'Subuh',
    'jadual.syuruk': 'Syuruk',
    'jadual.zohor': 'Zohor',
    'jadual.asar': 'Asar',
    'jadual.maghrib': 'Maghrib',
    'jadual.isyak': 'Isyak',
    'jadual.footer': 'Data dibekalkan secara rasmi oleh Jabatan Kemajuan Islam Malaysia (JAKIM) melalui waktusolat.app',

    // Derma
    'derma.title': 'Saham Akhirat Berterusan',
    'derma.subtitle': 'Infak & Sedekah',
    'derma.desc': 'NIYYAH dibina dengan satu matlamat: Memudahkan ibadah umat Islam. Platform ini kekal percuma dan tanpa iklan selamanya hasil sumbangan anda.',
    'derma.amount_label': 'Pilih Jumlah Infak',
    'derma.amount_desc': 'Sumbangan anda digunakan untuk kos server dan pembangunan API.',
    'derma.custom_amount': 'Jumlah lain...',
    'derma.pay_btn': 'Teruskan ke Pembayaran',
    'derma.secure': 'Secure Payment via ToyyibPay',
    'derma.why_title': 'Kenapa Menyokong NIYYAH?',
    'derma.reason1_title': 'Tanpa Iklan Selamanya',
    'derma.reason1_desc': 'Ibadah anda tidak akan diganggu oleh iklan komersial yang tidak relevan.',
    'derma.reason2_title': 'Pembangunan Pantas',
    'derma.reason2_desc': 'Dana digunakan untuk menambah 60+ fungsi yang dirancang dalam roadmap.',
    'derma.reason3_title': 'Infrastruktur Tinggi',
    'derma.reason3_desc': 'Server yang stabil memastikan waktu solat dan data Quran sentiasa tepat.',
    'derma.reason4_title': 'Dukungan Komuniti',
    'derma.reason4_desc': 'Memastikan ahli komuniti kurang berkemampuan mendapat akses alat Islamik terbaik.',
    'derma.hadith': '"Apabila mati seorang manusia, terputuslah daripadanya amalannya kecuali tiga perkara: sedekah jariah, ilmu yang diambil manfaat daripadanya, atau anak soleh yang mendoakannya." (Hadis Riwayat Muslim)',
    'derma.sim_alert': 'Menghubungkan ke ToyyibPay untuk jumlah RM{amount}... (Simulasi)',

    // Iqra
    'iqra.title': 'Iqra\' Digital',
    'iqra.tag': 'Program Belajar Al-Quran',
    'iqra.desc': 'Kurikulum sistematik untuk memulakan langkah pertama mengenal Kalamullah.',
    'iqra.step1': 'Pilih Tahap',
    'iqra.step2': 'Dengar Audio',
    'iqra.step3': 'Latih Tajwid',
    'iqra.level_suffix': 'Tahap {num}',
    'iqra.modul_suffix': '{num} Modul',
    'iqra.back': 'Kembali ke Koleksi',
    'iqra.page_suffix': 'Muka {num}',
    'iqra.click_tip': 'Klik huruf untuk dengar sebutan',
    'iqra.sound_label': 'Bunyi',
    'iqra.next_page': 'Muka surat seterusnya',
    'iqra.tip_title': 'Tip Pembelajaran',
    'iqra.technique': 'Teknik Sebutan',
    'iqra.goal_title': 'Matlamat Muka Surat',
    'iqra.goal_desc': 'Dapat membezakan sebutan huruf tunggal di atas dengan makhraj yang betul (tempat keluar huruf).',
    'iqra.finish_btn': 'Selesai Mengaji Muka Ini',
    'iqra.empty_title': 'Kandungan Belum Tersedia',
    'iqra.empty_desc': 'Modul ini dalam proses pengemaskinian oleh Team Niyyah.',
    'iqra.other_level': 'Pilih Level Lain',

    // Muqaddam
    'muqaddam.title': 'Muqaddam Digital',
    'muqaddam.tag': 'Kurikulum Hafazan Tradisional',
    'muqaddam.desc': 'Koleksi surah lazim Juz Amma dengan audio berkualiti dan panduan tajwid asas untuk pemula.',
    'muqaddam.back': 'Kembali ke Senarai Surah',
    'muqaddam.loading': 'Memuat Muat Turun Kalamullah...',
    'muqaddam.tajwid_title': 'Bantuan Tajwid',
    'muqaddam.qari_title': 'Qari Pilihan',
    'muqaddam.qari_desc': 'Bacaan yang perlahan dan jelas, sesuai untuk tujuan pembelajaran hafazan.',
    'muqaddam.start_read': 'Mula Baca',
    'muqaddam.rule.ghunnah': 'Ghunnah',
    'muqaddam.rule.ghunnah_desc': 'Dengungkan suara di pangkal hidung selama 2 harakat (nun/mim mati).',
    'muqaddam.rule.mad': 'Mad Asli',
    'muqaddam.rule.mad_desc': 'Panjangkan suara selama 2 harakat.',
    'muqaddam.rule.qalqalah': 'Qalqalah',
    'muqaddam.rule.qalqalah_desc': 'Pantulan suara apabila huruf Qalqalah mati (ba, jim, dal, tha, qaf).',

    // Kelas
    'kelas.title': 'Hab Ilmu Niyyah',
    'kelas.tag': 'Platform Kelas Online',
    'kelas.desc': 'Satu tempat di mana sesiapa boleh berkongsi ilmu dan belajar apa sahaja yang bermanfaat.',
    'kelas.my_classes': 'Kelas Saya',
    'kelas.create_new': 'Buat Kelas Baru',
    'kelas.search_placeholder': 'Cari kelas, topik atau nama guru...',
    'kelas.all_categories': 'Semua Kategori',
    'kelas.all_levels': 'Semua Tahap',
    'kelas.filter_all': 'semua',
    'kelas.filter_free': 'percuma',
    'kelas.filter_paid': 'berbayar',
    'kelas.unlimited': 'Unlimited',
    'kelas.students': 'Murid',
    'kelas.free_label': 'Percuma',
    'kelas.empty_title': 'Tiada Kelas Dijumpai',
    'kelas.empty_desc': 'Cuba tukar filter atau carian anda.',
    'kelas.reset_btn': 'Set Semula',

    // Komuniti
    'komuniti.title': 'Kisah Ummah',
    'komuniti.subtitle': 'Dukungan & Inspirasi Sesama Muslim',
    'komuniti.share_btn': 'Kongsi Kisah',
    'komuniti.cancel_btn': 'Batal',
    'komuniti.form_title': 'Tajuk Kisah',
    'komuniti.form_title_placeholder': 'Contoh: Hijrah Saya Pada Umur 40',
    'komuniti.form_category': 'Kategori',
    'komuniti.form_content': 'Kandungan Kisah',
    'komuniti.form_content_placeholder': 'Tuliskan kisah anda untuk menginspirasi pengguna lain...',
    'komuniti.form_submit': 'Hantar Ke Papan Cerita',
    'komuniti.loading': 'Tengah memuatkan kisah ummah...',
    'komuniti.anon': 'Hamba Allah',
    
    // Common
    'common.back': 'Kembali',
    'common.loading': 'Memuatkan...',
    'common.error': 'Ralat',
    'common.search': 'Cari...',
    'common.read_more': 'Baca Seterusnya',
    'common.view_all': 'Lihat Semua',
    'common.on': 'Buka',
    'common.off': 'Tutup',
    'common.suggested': 'Saranan',
  },
  en: {
    'nav.more': 'More',
    'nav.learn': 'Learn',
    'nav.pray': 'Pray',
    'nav.ummah': 'Ummah',
    'nav.search': 'Search...',
    'nav.home': 'Dashboard',
    'nav.mualaf': 'Convert Hub',
    'nav.quran': 'Al-Quran',
    'nav.iqra': 'Iqra\'',
    'nav.muqaddam': 'Muqaddam',
    'nav.hadis': 'Hadith',
    'nav.jadual': 'Prayer Times',
    'nav.tracker': 'Tracker',
    'nav.ramadan': 'Ramadan',
    'nav.zikir': 'Dhikr',
    'nav.99names': '99 Names',
    'nav.zakat': 'Zakat',
    'nav.kiblat': 'Qibla',
    'nav.doa': 'Dua',
    'nav.sirah': 'Seerah',
    'nav.kelas': 'Online Class',
    'nav.komuniti': 'Community',
    'nav.derma': 'Donate',
    'nav.tetapan': 'Settings',
    'nav.about': 'About Developer',
    'nav.login': 'Sign In',
    'nav.logout': 'Sign Out',
    'nav.saham': 'Shares',
    'nav.menu': 'Main Menu',
    'nav.dana': 'Operating Fund',
    'nav.infark': 'DONATE NOW',
    'nav.dana_desc': 'Niyyah stays ad-free through your contributions',
    'nav.tagline': 'Ummah Enlightened',

    'mualaf.title': 'Convert Hub',
    'mualaf.subtitle': 'Revert Guidance Center',
    'mualaf.desc': 'Simple, step-by-step guidance for your faith journey.',
    'mualaf.tab.basics': 'Basics of Worship',
    'mualaf.tab.doa': 'Daily Dua',
    'mualaf.tab.solat': 'Prayer Guide',
    'mualaf.tab.quran': 'Quran Transliteration',
    'mualaf.tab.support': 'Emotional Support',
    'mualaf.tab.community': 'Mentors',
    'mualaf.module.type': 'Learning Module',
    'mualaf.rumi.notice': 'This section is specially for those who are not yet proficient in reading Arabic text. Use the Romanized text as temporary guidance.',
    'mualaf.rumi.label': 'Romanized Text',
    'mualaf.maksud.label': 'Meaning',
    'mualaf.motivation.title': 'Daily Motivation',
    'mualaf.qa.title': 'Q&A Space (Anonymous)',
    'mualaf.qa.desc': 'Ask your questions anonymously. Our mentors will answer privately.',
    'mualaf.qa.placeholder': 'Example: How do I face my family who doesn\'t know I embraced Islam?',
    'mualaf.qa.submit': 'Send Question',
    'mualaf.qa.login_required': 'Please sign in to ask.',
    'mualaf.qa.history': 'Your Questions',
    'mualaf.qa.waiting': 'Waiting for Answer...',
    'mualaf.qa.mentor_reply': 'Mentor\'s Answer',
    'mualaf.community.chat': 'Revert Chat Room',
    'mualaf.community.chat_desc': 'Private community to discuss with fellow journeyers.',
    'mualaf.community.mentors': 'Registered Mentors',
    'mualaf.community.online': 'Online Now',
    'mualaf.community.verified': 'Verified Admin',
    'mualaf.community.chat_btn': 'Chat',
    'mualaf.community.no_mentors': 'Mentor registration in progress',
    'mualaf.emotion_tip': 'Emotional Tip',
    'mualaf.emotion_text': 'Practice the dhikr "La ilaha illa Allah" (There is no god but Allah) when feeling anxious. It provides extraordinary peace to the heart.',
    'mualaf.community.tg': 'Telegram Group',
    'mualaf.community.tg_note': 'Admin Verification Required',
    'mualaf.community.wa': 'WhatsApp Support',
    'mualaf.community.wa_note': 'Fast Response (24/7)',
    'mualaf.community.lecturer': 'Religious Lecturer',
    'mualaf.community.book_btn': 'Book Session',
    'mualaf.solat.title': 'Step-by-Step Prayer Guide',
    'mualaf.solat.subtitle': 'Complete guidance from Intention to Salam',
    'mualaf.solat.important': 'Important Notes',
    'mualaf.solat.step1.title': 'Intention for Prayer',
    'mualaf.solat.step1.desc': 'Intention in the heart according to the prayer being performed.',
    'mualaf.solat.step2.title': 'Takbiratul Ihram',
    'mualaf.solat.step2.desc': 'Raising the hands and saying "Allahu Akbar".',
    'mualaf.solat.step3.title': 'Recitation of Al-Fatihah',
    'mualaf.solat.step3.desc': 'An obligatory pillar that must be recited calmly.',
    'mualaf.solat.step4.title': 'Rukuk',
    'mualaf.solat.step4.desc': 'Bowing the body with hands on the knees.',
    'mualaf.solat.step5.title': 'I\'tidal',
    'mualaf.solat.step5.desc': 'Standing upright again after rukuk.',
    'mualaf.solat.step6.title': 'Sujud',
    'mualaf.solat.step6.desc': 'Placing forehead, nose, palms, knees and toes on the floor.',
    'mualaf.solat.note1': 'Ensure body, clothing and place are clean from impurities.',
    'mualaf.solat.note2': 'Facing the direction of Qibla (Use Qibla function in app).',
    'mualaf.solat.note3': 'Covering aurah/modesty perfectly.',
    'mualaf.solat.note4': 'Correct prayer time has started.',

    // Dashboard
    'dash.title': 'Home',
    'dash.greeting': 'Assalamualaikum, {name}',
    'dash.greeting_default': 'Assalamualaikum, Ya Akhi/Ukhti',
    'dash.prayer_current': 'Current Prayer',
    'dash.prayer_next': 'Next Prayer',
    'dash.prayer_waiting': 'Calculating time...',
    'dash.prayer_running': 'In Progress ({time}m)',
    'dash.prayer_remaining': '{time} remaining',
    'dash.widget_btn': 'ENABLE WIDGET',
    'dash.jadual_today': 'Today\'s Schedule',
    'dash.jadual_full': 'View Full Schedule',
    'dash.ayat_title': 'Daily Quran Verse',
    'dash.ayat_verse': 'O you who have believed, seek help through patience and prayer. Indeed, Allah is with the patient.',
    'dash.tafsir_btn': 'VIEW TAFSIR',
    'dash.audio_btn': 'LISTEN AUDIO',
    'dash.hadis_title': 'Hadith Library',
    'dash.hadis_loading': 'Loading message of the Messenger...',
    'dash.story_title': 'Ummah Inspiration',
    'dash.story_author': 'By: {name}',
    'dash.story_sample': '"The story of how honesty brought me unexpected blessings..."',
    'dash.status_active': 'Status: Active Member',

    // Ramadan
    'ramadan.title': 'Ramadan Dashboard',
    'ramadan.subtitle': 'Ramadan Al-Mubarak 1447H',
    'ramadan.desc': 'A month full of mercy, forgiveness, and release from the hellfire. Track your deeds every day.',
    'ramadan.select_day': 'Select Day',
    'ramadan.day_count': 'Day {num}',
    'ramadan.checklist': 'Deeds Checklist',
    'ramadan.progress': 'Progress',
    'ramadan.deed.fasting': 'Fasting',
    'ramadan.deed.tarawih': 'Tarawih Prayer',
    'ramadan.deed.tadarus': 'Quran Tadarus',
    'ramadan.deed.sedekah': 'Charity',
    'ramadan.deed.witir': 'Witr Prayer',
    'ramadan.deed.iktikaf': 'Itikaf',
    'ramadan.niat.title': 'Intention for Ramadan Fasting',
    'ramadan.niat.arabic': 'نَوَيْتُ صَوْمَ غَدٍ عَنْ أَدَاءِ فَرْضِ شَهْرِ رَمَضَانَ هَذِهِ السَّنَةِ لِلَّهِ تَعَالَى',
    'ramadan.niat.transliteration': 'Nawaitu sawma ghadin \'an ada\'i fardhi shahri Ramadhana hadhihis-sanati lillahi ta\'ala.',
    'ramadan.niat.meaning': 'I intend to fast tomorrow for the fulfillment of the obligatory Ramadan fast this year for the sake of Allah the Almighty.',
    'ramadan.break.title': 'Dua for Breaking Fast',
    'ramadan.break.arabic': 'اللَّهُمَّ لَكَ صُمْتُ وَبِكَ آمَنْتُ وَعَلَى رِزْقِكَ أَفْطَرْتُ',
    'ramadan.break.transliteration': 'Allahumma laka sumtu wa bika amantu wa \'ala rizqika aftartu.',
    'ramadan.break.meaning': 'O Allah, for You I fasted, in You I believe, and with Your provision I break my fast.',
    'ramadan.quote.title': 'Pearls of Wisdom',
    'ramadan.quote.text': '"Whoever fasts Ramadan out of faith and in the hope of reward, his previous sins will be forgiven."',
    'ramadan.quote.author': 'Narrated by Bukhari & Muslim',

    // Zakat
    'zakat.title': 'Zakat Calculator',
    'zakat.subtitle': 'Wealth Management & Blessings',
    'zakat.desc': 'Purify your wealth with Zakat. One of the five Pillars of Islam that ensures the economic balance of the Ummah.',
    'zakat.wealth_label': 'Total Accumulated Wealth (Savings/Investments)',
    'zakat.status_title': 'Zakat Status',
    'zakat.qualify_true': 'Your wealth is eligible for Zakat at a rate of 2.5%.',
    'zakat.qualify_false': 'Your wealth does not meet the nisab (RM {nisab}) currently.',
    'zakat.type_label': 'Please Select Zakat Type',
    'zakat.type.saving': 'Savings',
    'zakat.type.income': 'Income',
    'zakat.type.gold': 'Gold',
    'zakat.type.business': 'Business',
    'zakat.pay_label': 'Total Payable Amount',
    'zakat.info_rate': 'A rate of 2.5% is used for general wealth zakat calculation.',
    'zakat.pay_btn': 'Pay Now',
    'zakat.footer': 'This calculator provides ESTIMATED calculations only. Please refer to your respective State Zakat Center for more accurate calculations.',

    'prayer.fajr': 'Fajr',
    'prayer.syuruk': 'Sunrise',
    'prayer.dhuhr': 'Dhuhr',
    'prayer.asr': 'Asr',
    'prayer.maghrib': 'Maghrib',
    'prayer.isha': 'Isha',

    // Basics Modules
    'mualaf.syahadah.title': 'How to Recite the Shahada',
    'mualaf.syahadah.desc': 'The declaration of faith to enter Islam.',
    'mualaf.mandi.title': 'How to Perform Ghusl (Full Ablution)',
    'mualaf.mandi.desc': 'Spiritual purification after major ritual impurity.',
    'mualaf.wuduk.title': 'How to Perform Wudu (Ablution)',
    'mualaf.wuduk.desc': 'Ablution before performing prayer.',
    'mualaf.tayammum.title': 'How to Perform Tayammum (Dry Ablution)',
    'mualaf.tayammum.desc': 'Purification without water in emergency cases.',
    'mualaf.solat_module.title': 'How to Pray (Complete Guide)',
    'mualaf.solat_module.desc': 'Basic movements of obligatory prayers.',
    'mualaf.puasa.title': 'How to Fast in Ramadan',
    'mualaf.puasa.desc': 'Worship by refraining from food/drink in the holy month.',
    'mualaf.zakat.title': 'How to Pay Zakat Fitrah',
    'mualaf.zakat.desc': 'Purification of wealth and helping those in need.',
    'mualaf.korban.title': 'Sacrifice & Aqiqah Guide',
    'mualaf.korban.desc': 'Ritual sacrifice as a sign of gratitude.',

    // Doa
    'doa.wakeup.title': 'Dua Upon Waking Up',
    'doa.wakeup.maksud': 'All praise is for Allah who gave us life after having taken it from us and unto Him is the resurrection.',
    'doa.toilet_in.title': 'Dua Before Entering Toilet',
    'doa.toilet_in.maksud': 'O Allah, I seek refuge with You from all offensive and wicked things.',
    'doa.toilet_out.title': 'Dua After Leaving Toilet',
    'doa.toilet_out.maksud': 'I ask Your forgiveness. All praise is for Allah who removed from me suffering and gave me health.',
    'doa.eat_before.title': 'Dua Before Eating',
    'doa.eat_before.maksud': 'O Allah, bless us in what You have provided for us and save us from the punishment of the Hellfire.',
    'doa.eat_after.title': 'Dua After Eating',
    'doa.eat_after.maksud': 'All praise is for Allah who has fed us and given us drink and made us Muslims.',
    'doa.house_out.title': 'Dua Upon Leaving House',
    'doa.house_out.maksud': 'In the name of Allah, I place my trust in Allah, and there is no might nor power except with Allah.',
    'doa.house_in.title': 'Dua Upon Entering House',
    'doa.house_in.maksud': 'O Allah, I ask You for the best entering and the best exiting. In the name of Allah we enter and in the name of Allah we exit and upon Allah our Lord we trust.',
    'doa.travel.title': 'Dua for Traveling',
    'doa.travel.maksud': 'Glory is to Him Who has subjected this to us, and we were not able to do it ourselves.',
    'doa.sleep.title': 'Dua Before Sleeping',
    'doa.sleep.maksud': 'In Your name O Allah, I live and I die.',
    'doa.protection.title': 'Dua for Protection',
    'doa.protection.maksud': 'I seek refuge in the perfect words of Allah from the evil of what He has created.',
    'doa.travel_ride.title': 'Musafir Dua',
    'doa.travel_ride.maksud': 'Glory be to Allah Who has subjected this to us, and we were not able to do it ourselves. And indeed to our Lord, we will return.',
    'doa.study.title': 'Dua for Knowledge',
    'doa.study.maksud': 'O my Lord, increase me in knowledge and expand my understanding.',
    'doa.rabbana.title': 'Rabbana Dua',
    'doa.rabbana.maksud': 'Our Lord, give us in this world [that which is] good and in the Hereafter [that which is] good and protect us from the punishment of the Fire.',

    // Quran
    'quran.fatihah.maksud': 'In the name of Allah, the Entirely Merciful, the Especially Merciful. [All] praise is [due] to Allah, Lord of the worlds...',
    'quran.ikhlas.maksud': 'Say: He is Allah, [who is] One. Allah, the Eternal Refuge...',
    'quran.falaq.maksud': 'Say: I seek refuge in the Lord of daybreak From the evil of that which He created...',
    'quran.nas.maksud': 'Say: I seek refuge in the Lord of mankind, The Sovereign of mankind...',
    'quran.kauthar.maksud': 'Indeed, We have granted you, [O Muhammad], al-Kawthar. So pray to your Lord and sacrifice [to Him alone]...',
    'quran.nasr.maksud': 'When the victory of Allah has come and the conquest. And you see the people entering into the religion of Allah in multitudes...',
    'quran.kursi.maksud': 'Allah - there is no deity except Him, the Ever-Living, the Sustainer of [all] existence...',

    // Quran Page
    'quran.title': 'Al-Quran',
    'quran.subtitle': 'Holy Book & Complete Guidance',
    'quran.search': 'Search Surah...',
    'quran.loading': 'Loading Surah...',
    'quran.juz': 'Juz {num}',
    'quran.verses': '{num} Verses',
    'quran.revelation_meccan': 'Meccan',
    'quran.revelation_medinan': 'Medinan',
    'quran.last_read': 'Last Read',
    'quran.info_btn': 'Surah Info',
    'quran.digital_title': 'Digital',
    'quran.hadith_quote': '"The best of you are those who learn the Quran and teach it." (HR. Bukhari)',
    'quran.translation_label': 'Verse Meaning',
    'quran.list_title': 'Surah Index',
    'quran.empty': 'No surah or verse found.',

    // Hadis Page
    'hadis.title': 'Hadith Library',
    'hadis.subtitle': 'Messages of the Prophet (SAW)',
    'hadis.search': 'Search hadith or topic...',
    'hadis.loading': 'Loading hadith...',
    'hadis.view_all': 'View All {book}',
    'hadis.collection_badge': 'Sahih & Curated Collection',
    'hadis.explore_desc': 'Explore in-depth discussion on {cat} based on verified narrations.',
    'hadis.status_sahih': 'Sahih',
    'hadis.transmission': 'Transmission',
    'hadis.translation_label': 'Verified Translation',
    'hadis.meaning_title': 'Meaning & Lessons',
    'hadis.explanation_title': 'Brief Commentary',
    'hadis.hints_title': 'Key Takeaways',

    // Doa Page
    'doa.title': 'Dua Collection',
    'doa.subtitle': 'The Weapon of the Believer',
    'doa.category.daily': 'Daily',
    'doa.category.prayer': 'Prayer',
    'doa.category.prophets': 'Prophets',
    'doa.category.protection': 'Protection',
    'doa.category.health': 'Health',
    'doa.category.knowledge': 'Knowledge & Provision',
    'doa.category.ramadan': 'Ramadan',
    'doa.all': 'All',
    'doa.my_saved': 'My Saved',
    'doa.add_btn': 'Add Dua',
    'doa.form_title': 'Dua Title',
    'doa.form_title_placeholder': 'Example: Dua for Ease',
    'doa.form_arabic_placeholder': 'Write in Arabic...',
    'doa.form_trans_placeholder': 'Example: Bismika Allahumma...',
    'doa.form_meaning_placeholder': 'Translation...',
    'doa.save_btn': 'Save',
    'doa.empty_title': 'Untitled Dua',

    // Settings
    'settings.title': 'Settings',
    'settings.profile': 'User Profile',
    'settings.language': 'App Language',
    'settings.location': 'Location & Prayer Zone',
    'settings.notifications': 'Azan Notifications',
    'settings.theme': 'Visual Theme',
    'settings.save_btn': 'Save Settings',
    'settings.subtitle': 'Manage your profile and reminders',
    'settings.status_active': 'Status: Active Member',
    'settings.display_name': 'Display Name',
    'settings.reminder_before': 'Reminder Before Azan',
    'settings.minutes': 'Minutes',
    'settings.success': 'SUCCESSFULLY SAVED!',
    'settings.saving': 'Saving...',
    'settings.support_title': 'Contribution / Infaq',
    'settings.support_desc': 'This application is a free community initiative. If you would like to support maintenance and development costs, you can contribute via the link below.',
    'settings.support_btn': 'Donate Now',

    // Tracker
    'tracker.title': 'Prayer Tracker',
    'tracker.subtitle': 'Consistency is Beautiful',
    'tracker.done': 'Completed',
    'tracker.pending': 'Not Marked Yet',
    'tracker.target': 'Today\'s Target',
    'tracker.quote': '"The most beloved deed to Allah is prayer at its proper time." (HR. Bukhari)',
    'tracker.reward_title': 'Today\'s Reward',
    'tracker.reward_desc': 'Increase your salawat upon the Prophet (PBUH) to add barakah to your day.',

    // Sirah
    'sirah.title': 'Prophetic Biography (Sirah)',
    'sirah.subtitle': 'Tracing the life of the noblest human, Prophet Muhammad PBUH, as a guide for all times.',
    'sirah.timeline': 'Islamic History Timeline',
    'sirah.epoch_1_title': 'Birth & Childhood',
    'sirah.epoch_1_desc': 'The Year of the Elephant, nursing by Halimah As-Sa\'diyah, and the passing of Aminah binti Wahab.',
    'sirah.epoch_2_title': 'Youth & Marriage',
    'sirah.epoch_2_desc': 'Honesty of Al-Amin as a merchant and the holy marriage to Khadijah binti Khuwailid.',
    'sirah.epoch_3_title': 'Prophethood (First Revelation)',
    'sirah.epoch_3_desc': 'The event at Cave Hira\', the visit of Jibril AS, and the start of secret preaching.',
    'sirah.epoch_4_title': 'Open Preaching & Opposition',
    'sirah.epoch_4_desc': 'Preaching at Mount Safa, opposition from Abu Lahab, and the persecution of the weak.',
    'sirah.author': 'Curated by {name}',
    'sirah.read_more': 'Read More',
    'sirah.footer_title': 'Journey Not Yet Completed',
    'sirah.footer_desc': 'We are in the process of adding more stories of the Prophet PBUH and his Companions RA.',
    'sirah.notify_btn': 'Remind Me',

    // Zikir
    'zikir.title': 'Dhikr & Tasbih',
    'zikir.subtitle': 'Calming the Heart by Remembering Allah',
    'zikir.tab.tasbih': 'Digital Tasbih',
    'zikir.tab.wird': 'Wird Collection',
    'zikir.counter.title': 'Total Recitals',
    'zikir.btn.click': 'Tap to Recite',
    'zikir.reset_confirm': 'Reset counter?',
    'zikir.vibration': 'Vibration {status}',
    'zikir.pagi': 'Morning Dhikr',
    'zikir.petang': 'Evening Dhikr',
    'zikir.mathurat': 'Ma\'thurat Sughra',
    'zikir.meaning.subhanallah': 'Glory be to Allah',
    'zikir.meaning.alhamdulillah': 'Praise be to Allah',
    'zikir.meaning.allahuakbar': 'Allah is Greatest',
    'zikir.meaning.lailahaillallah': 'There is no god but Allah',
    'zikir.meaning.astaghfirullah': 'I seek forgiveness from Allah',

    // 99 Names
    'names.title': 'Asma\'ul Husna',
    'names.subtitle': 'The 99 Beautiful Names of Allah',
    'names.quote': '"And to Allah belong the best names, so invoke Him by them." (Surah Al-A\'raf: 180)',
    'names.search': 'Search Beautiful Names...',
    'names.detail_btn': 'Detail',

    // Qibla
    'qibla.title': 'Qibla',
    'qibla.subtitle': 'Worship Direction Anywhere',
    'qibla.direction': 'Qibla Direction',
    'qibla.activate_btn': 'Activate Compass Sensor',
    'qibla.notice': 'Place your phone on a flat surface. Ensure your GPS is active for maximum accuracy.',

    // Jadual Solat
    'jadual.title': 'Prayer Schedule',
    'jadual.subtitle': 'Official JAKIM Prayer Times',
    'jadual.location_btn': 'Use My Location',
    'jadual.locating': 'Locating...',
    'jadual.detect_error': 'Failed to detect location. Please ensure location permissions are granted.',
    'jadual.print': 'Print Schedule',
    'jadual.date_day': 'Date & Day',
    'jadual.imsak': 'Imsak',
    'jadual.subuh': 'Fajr',
    'jadual.syuruk': 'Sunrise',
    'jadual.zohor': 'Dhuhr',
    'jadual.asar': 'Asr',
    'jadual.maghrib': 'Maghrib',
    'jadual.isyak': 'Isha',
    'jadual.footer': 'Data officially provided by Department of Islamic Development Malaysia (JAKIM) via waktusolat.app',

    // Derma
    'derma.title': 'Continuous Afterlife Investment',
    'derma.subtitle': 'Contribution & Charity',
    'derma.desc': 'NIYYAH is built with one goal: To facilitate worship for Muslims. This platform remains free and ad-free forever thanks to your contributions.',
    'derma.amount_label': 'Choose Contribution Amount',
    'derma.amount_desc': 'Your contributions are used for server costs and API development.',
    'derma.custom_amount': 'Other amount...',
    'derma.pay_btn': 'Continue to Payment',
    'derma.secure': 'Secure Payment via ToyyibPay',
    'derma.why_title': 'Why Support NIYYAH?',
    'derma.reason1_title': 'Ad-Free Forever',
    'derma.reason1_desc': 'Your worship will not be interrupted by irrelevant commercial advertisements.',
    'derma.reason2_title': 'Fast Development',
    'derma.reason2_desc': 'Funds are used to add 60+ planned features in the roadmap.',
    'derma.reason3_title': 'High Infrastructure',
    'derma.reason3_desc': 'Stable servers ensure prayer times and Quran data are always accurate.',
    'derma.reason4_title': 'Community Support',
    'derma.reason4_desc': 'Ensuring less fortunate community members have access to the best Islamic tools.',
    'derma.hadith': '"When a man dies, his deeds come to an end except for three: a continuous charity, knowledge by which people benefit, or a righteous child who prays for him." (Narrated by Muslim)',
    'derma.sim_alert': 'Connecting to ToyyibPay for RM{amount}... (Simulation)',

    // Iqra
    'iqra.title': 'Digital Iqra\'',
    'iqra.tag': 'Quran Learning Program',
    'iqra.desc': 'A systematic curriculum to take the first steps in knowing the Word of Allah.',
    'iqra.step1': 'Choose Level',
    'iqra.step2': 'Listen to Audio',
    'iqra.step3': 'Practice Tajweed',
    'iqra.level_suffix': 'Level {num}',
    'iqra.modul_suffix': '{num} Modules',
    'iqra.back': 'Back to Collection',
    'iqra.page_suffix': 'Page {num}',
    'iqra.click_tip': 'Click letters to hear pronunciation',
    'iqra.sound_label': 'Sound',
    'iqra.next_page': 'Next page',
    'iqra.tip_title': 'Learning Tip',
    'iqra.technique': 'Pronunciation Technique',
    'iqra.goal_title': 'Page Goal',
    'iqra.goal_desc': 'Able to distinguish the pronunciation of single letters above with the correct makhraj (letter exit point).',
    'iqra.finish_btn': 'Finished this page',
    'iqra.empty_title': 'Content Not Yet Available',
    'iqra.empty_desc': 'This module is in the process of being updated by Team Niyyah.',
    'iqra.other_level': 'Choose Other Level',

    // Muqaddam
    'muqaddam.title': 'Digital Muqaddam',
    'muqaddam.tag': 'Traditional Memorization Curriculum',
    'muqaddam.desc': 'A collection of common Juz Amma surahs with quality audio and basic tajweed guidance for beginners.',
    'muqaddam.back': 'Back to Surah List',
    'muqaddam.loading': 'Downloading the Word of Allah...',
    'muqaddam.tajwid_title': 'Tajweed Help',
    'muqaddam.qari_title': 'Selected Qari',
    'muqaddam.qari_desc': 'Slow and clear recitation, suitable for memorization learning purposes.',
    'muqaddam.start_read': 'Start Reading',
    'muqaddam.rule.ghunnah': 'Ghunnah',
    'muqaddam.rule.ghunnah_desc': 'Nasalization in the back of the nose for 2 counts (noon/meem sakinah).',
    'muqaddam.rule.mad': 'Mad Asli',
    'muqaddam.rule.mad_desc': 'Extend the sound for 2 counts.',
    'muqaddam.rule.qalqalah': 'Qalqalah',
    'muqaddam.rule.qalqalah_desc': 'Sound reflection when a Qalqalah letter is stagnant (ba, jim, dal, tha, qaf).',

    // Kelas
    'kelas.title': 'Niyyah Knowledge Hub',
    'kelas.tag': 'Online Class Platform',
    'kelas.desc': 'A place where anyone can share knowledge and learn anything beneficial.',
    'kelas.my_classes': 'My Classes',
    'kelas.create_new': 'Create New Class',
    'kelas.search_placeholder': 'Search classes, topics or teacher names...',
    'kelas.all_categories': 'All Categories',
    'kelas.all_levels': 'All Levels',
    'kelas.filter_all': 'all',
    'kelas.filter_free': 'free',
    'kelas.filter_paid': 'paid',
    'kelas.unlimited': 'Unlimited',
    'kelas.students': 'Students',
    'kelas.free_label': 'Free',
    'kelas.empty_title': 'No Classes Found',
    'kelas.empty_desc': 'Try changing your filter or search.',
    'kelas.reset_btn': 'Reset',

    // Komuniti
    'komuniti.title': 'Ummah Stories',
    'komuniti.subtitle': 'Support & Inspiration Among Fellow Muslims',
    'komuniti.share_btn': 'Share Story',
    'komuniti.cancel_btn': 'Cancel',
    'komuniti.form_title': 'Story Title',
    'komuniti.form_title_placeholder': 'Example: My Hijrah at Age 40',
    'komuniti.form_category': 'Category',
    'komuniti.form_content': 'Story Content',
    'komuniti.form_content_placeholder': 'Write your story to inspire other users...',
    'komuniti.form_submit': 'Post to Story Board',
    'komuniti.loading': 'Loading ummah stories...',
    'komuniti.anon': 'Servant of Allah',

    // Common
    'common.back': 'Back',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.search': 'Search...',
    'common.read_more': 'Read More',
    'common.view_all': 'View All',
    'common.on': 'On',
    'common.off': 'Off',
    'common.suggested': 'Suggested',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem('niyyah_lang') as Language) || 'ms';
  });

  useEffect(() => {
    localStorage.setItem('niyyah_lang', language);
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
